### ISSUE TITLE
Cells which create bokeh plots do not get saved

### ISSUE THREAD

**Issue by jacobtomlinson** [bokeh/jupyterlab_bokeh#29]
I've encountered an issue where all cells which produce a bokeh plot in Jupyter Lab do not get saved.

## Versions

```
$ jupyter labextension list
JupyterLab v0.31.8
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.33.2  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.1  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0  enabled  OK
```

## Reproducing

- Create a new notebook
- Create a cell with the following code

```python
from bokeh.io import show, output_notebook
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure
from bokeh.sampledata.commits import data
from bokeh.transform import jitter

output_notebook()

DAYS = ['Sun', 'Sat', 'Fri', 'Thu', 'Wed', 'Tue', 'Mon']

source = ColumnDataSource(data)

p = figure(plot_width=800, plot_height=300, y_range=DAYS, x_axis_type='datetime',
           title="Commits by Time of Day (US/Central) 2012-2016")

p.circle(x='time', y=jitter('day', width=0.6, range=p.y_range),  source=source, alpha=0.3)

p.xaxis[0].formatter.days = ['%Hh']
p.x_range.range_padding = 0
p.ygrid.grid_line_color = None

show(p)
```

- Save the notebook
- Restart Jupyter Lab
- Open the notebook
- The cell is missing

**Comment by jacobtomlinson** [comment]
Further investigation shows that if I then run `output_notebook()` again in a new cell and then close and reopen the notebook the missing cell reappears.

**Comment by tjcrone** [comment]
I am also experiencing this. The cells are saved, but if any have bokeh output, those cells are not shown when the notebook is opened. One solution is to clear the outputs, save, and reopen. Also not ideal though.
## Versions
```
jovyan@jupyter-tjcrone:~$ jupyter labextension list
JupyterLab v0.31.12
Known labextensions:
   app dir: /opt/conda/share/jupyter/lab
@jupyter-widgets/jupyterlab-manager
        @jupyter-widgets/jupyterlab-manager v0.34.0  enabled  OK
@jupyterlab/hub-extension
        @jupyterlab/hub-extension v0.8.1  enabled  OK
@pyviz/jupyterlab_holoviews
        @pyviz/jupyterlab_holoviews v0.3.3  enabled  OK
jupyterlab_bokeh
        jupyterlab_bokeh v0.4.0  enabled  OK
```

**Comment by canavandl** [comment]
Looking at the browser console while reloading the page, there's the following exception:

```
index.js:220 TypeError: Cannot read property 'embed' of undefined
    at n.renderModel (renderer.js:71)
    at t.createRenderedMimetype (widget.js:394)
    at t.createOutputItem (widget.js:367)
    at t._insertOutput (widget.js:335)
    at new t (widget.js:168)
    at new t (widget.js:432)
    at t.createCodeCell (widget.js:531)
    at t._createCodeCell (widget.js:399)
    at t._insertCell (widget.js:377)
    at widget.js:343
```

Specifically window.Bokeh is undefined here https://github.com/bokeh/jupyterlab_bokeh/blob/master/src/renderer.ts#L100 because the mimerenderer is executed before BokehJS has loaded and been atttached to window. Then the exception causes the cell to not be renderered :( (You can get the cells to load/plots to render by closing/reopening the notebook)

The check should assert ``window.Bokeh != undefined & window.Bokeh.embed.kernels !== undefined)``

**Comment by canavandl** [comment]
@jacobtomlinson @tjcrone 

This issue was resolved in #34 and a new jupyterlab_bokeh=0.4.1 lab extension has been published. Please open a new issue if there are still problems.

**Comment by chunkylover7** [comment]
I'm still seeing this issue with every restart of any bokeh plot using "output_notebook"  with the following jupyter lab and lab extensions versions, am I missing any extensions or down reved where there is a more recent version?  These are all installed from "jupyter labextension install" in the last month or less:

~> jupyter labextension list                                                                                                                                                                                        
JupyterLab v1.1.4
Known labextensions:
app dir: <...>/.pyenv/versions/anaconda3-2019.10/share/jupyter/lab
        @bokeh/jupyter_bokeh v1.1.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        bqplot v0.5.1  enabled  OK
        jupyterlab-plotly v1.3.0  enabled  OK
        jupyterlab_bokeh v1.0.0  enabled  OK
        plotlywidget v1.3.0  enabled  OK
        qgrid v1.1.1  enabled  OK

Any advice, recommendations, is appreciated.  Please let me know if additional info is required.

Thanks!
-chunkylover

**Comment by bryevdv** [comment]
cc @mattpap 

@chunkylover7 I don't think you should have both `jupyterlab_bokeh` (old) and `@bokeh/jupyter_bokeh` (new) installed at the same time, you should first try and see what happens with just the most recent jupyter bokeh extension installed.

**Comment by chunkylover7** [comment]
Thanks for the reply, I was using only @bokeh/jupyter_bokeh when I first noticed the issue.   I found the github issue and the way I read the fix was that jupyterlab_bokeh had the patch and since I never used that extension thought it was the latest and loaded it alongside “@boken/…” this past weekend (1/5/2020) but obviously didn’t help.

I just shut down Jupyter Lab and uninstalled jupyterlab_bokeh extension so now I’m running the same config as when first discovered the issue (see below)  and still have the problem (see screenshot below).  Note that a cell with a large block of bokeh code is missing just below the “Loading BokehJS…” message.

JupyterLab v1.1.4
Known labextensions:
   app dir: /Users/.pyenv/versions/anaconda3-2019.10/share/jupyter/lab
        @bokeh/jupyter_bokeh v1.1.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v1.0.3  enabled  OK
        bqplot v0.5.1  enabled  OK
        jupyterlab-plotly v1.3.0  enabled  OK
        plotlywidget v1.3.0  enabled  OK
        qgrid v1.1.1  enabled  OK


[cid:image001.png@01D5C6EB.C5DDF690]

Let me know if you need any more info.

Now that I know how to work around it the problem is minor (reload output_notebook and restart the notebook) but before I found the work-around I was panicked as I had just finished a fairly complicated plot and thought Jupyter Lab had lost it forever!

Thanks!
-mike

**Comment by bryevdv** [comment]
@chunkylover7 The image did not seem to make it through, can you upload it directly on the  GH web UI? 

cc @mattpap This shows up if I reload a saved notebook in lab with 1.4.0 and the 1.1 extension:

<img width="744" alt="Screen Shot 2020-01-09 at 11 08 51 AM" src="https://user-images.githubusercontent.com/1078448/72097113-812cba80-32d0-11ea-9457-49737c23b1ac.png">

**Comment by chunkylover7** [comment]
Here is a screen cap showing the issue where bokeh is stuck loading bokehjs preventing cell below it from loading

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/10792818/72101394-315aed00-32ea-11ea-8c51-544af611c995.png">

**Comment by chunkylover7** [comment]
Yes, just uploaded it in the issue page.

Thanks for looking at this!
-mike

**Comment by bryevdv** [comment]
cc @mattpap do you have any thoughts on this?

**Comment by mattpap** [comment]
I did some rudimentary debugging when working on widgets integration, but I don't remember right now my conclusions on this issue. I will give this another look when time permits.

**Comment by dbk123** [comment]
Any update on this?  I just spent several hours thinking I was going crazy trying to find the missing cells.  Now I get the following error when reopening the notebook for each cell that should contain bokeh output: 

Javascript Error: Error rendering Bokeh model: could not find #078d3e4f-4b49-4ce8-9002-53355d95ff50 HTML tag

**Comment by bryevdv** [comment]
@dbk123 I don't know what's changed on the Jupyter side to break things. Please make an issue in the main repo about this, since it will have much better visibility there. And please be detailed and thorough and describe as many failure scenarios with complete steps to reproduce, etc. as possible for each. Debugging Jupyter issues is a nightmare and we will absolutely need everyone's help.

**Comment by chunkylover7** [comment]
Hello –

Today I noticed the same behavior but in a notebook with bqplot code which I had not seen before.  I used bqplot when I first started using Jupyter but then changed to Bokeh which is when I first noticed this maybe 6-8 months ago and I only ever saw it in my bokeh notebooks until today when I opened one of my older plots using bqplot.

It looked to be the same as I see with bokeh code, all cells with bqplot code were missing and only python code cells displayed.  I then executed one cell block that had all of the notebook’s import statements as well as Jupyter’s autoreload extension and when it returned, closed the notebook and reopened and everything came back.

I’ll keep testing to see if it happens again with bqplot as again, this was the first time I’ve seen it in those notebooks but if it does it could hint at being a Jupyter issue.

Are you using Jupyter Lab’s autoreload extension in your affected notebook(s)?

**Comment by dbk123** [comment]
I am not using the autoreload extension (at least I don't think so).  Since my posting, I have been difficulty replicating this in a consistent manner so that I post in the main repo as requested by Bryan.  I switched back to matplotlib for some stuff I had to get done, but am back to using bokeh now.

**Comment by bryevdv** [comment]
@chunkylover7 @dbk123 this issue should be resolved on master, we will have micro releases out in the next few weeks.

**Comment by dbk123** [comment]
Awesome!

**Comment by jbootsma** [comment]
I am seeing this exact behavior in a new installation using Bokeh 2.0.1 and JupyterLab 2.1.0

Bringing up the java script debugger shows 

> Bokeh: ERROR: autoload.js configured with elementid '1001' but no matching script tag was found. 

Browser is firefox v75.0

$ jupyter labextension list
   app dir: f:\dev\machine-learning\r-learning\nbenv\share\jupyter\lab
        @bokeh/jupyter_bokeh v2.0.1 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
JupyterLab v2.1.0
Known labextensions:

I can also confirm that running output_notebook() from anywhere within jupyter lab causes all Bokeh content to load properly again when notebooks are re-opened after that point.
